### ISSUE TITLE
请问怎么配置打印某个类的方法呢

### ISSUE THREAD

**Issue by CrassusX** [omxcodec/OCMethodTrace#1]
如：
USER_CLASS_LIST
QLVideoDetailViewController 
    TraceMode  3
    TraceFlag     4
MethodBlackList 
MethodWhiteList
我只想打印某个类的所有发放，但是很多情况不管怎么配置都会crash，还是之间的打印方法日志比较简单，这个又繁琐，又不知道怎么配置

**Comment by omxcodec** [comment]
嗯，有在某些情况下会导致崩溃。
比如有些proxy的类等会导致崩溃，需要过滤掉；还有dealloc时候调用方法也可以。还需要进一步改善。

麻烦你给我这些东西：
1 对应的ipa
2 出现问题时你配置的MDConfig.plist文件，整个给我
3 把崩溃日志发我一下

**Comment by omxcodec** [comment]
> 只想打印某个类的所有发放，但是很多情况不管怎么配置都会crash，还是之间的打印方法日志比较简单，这个又繁琐，又不知道怎么配置

这个QLVideoDetailViewController类属于腾讯视频。不仅这个类会导致崩溃，它很多类都会导致。


崩溃的原因：
腾讯视频内部swizzle了-[NSObject forwardingTargetForSelector:]方法，替换成
-[NSObject QLForwardingTargetForSelector:]
但是OCMethodTrace内部其实也swizzle该方法-[NSObject forwardingTargetForSelector:]，替换成
-[NSObject omt_forwardingTargetForSelector:]
我们的方法被腾讯视频的覆盖了...

可以使用IDA看腾讯视频的反汇编：
void __cdecl +[NSObject switchAllMethod](NSObject_meta *self, SEL a2)
{
   .......
  objc_msgSend(
    &OBJC_CLASS___NSObject,
    "swizzleMethod:withMethod:",
    "forwardingTargetForSelector:",
    "QLForwardingTargetForSelector:");
   .......
}
live4iphone.app/Frameworks/QNBAutomatic.framework
id __cdecl -[NSObject QLForwardingTargetForSelector:](NSObject *self, SEL a2, SEL a3)
{
  SEL v3; // x20
  NSObject *v4; // x22
  void *v5; // x0
  __int64 v6; // x0
  void *v7; // x19
  QLNotResponceSelectorHander *v8; // x0
  QLNotResponceSelectorHander *v9; // x22
  __int64 v10; // x0
  __int64 v11; // x23
  void *v12; // x0
  void *v13; // x0

  v3 = a3;
  v4 = self;
  v5 = objc_msgSend(self, "class");
  v6 = NSStringFromClass(v5);
  v7 = (void *)objc_retainAutoreleasedReturnValue(v6);
  if ( (unsigned int)objc_msgSend(v7, "hasPrefix:", CFSTR("QL")) )
  {
    v8 = (QLNotResponceSelectorHander *)objc_msgSend(&OBJC_CLASS___QLNotResponceSelectorHander, "alloc");
    v9 = (QLNotResponceSelectorHander *)objc_msgSend(v8, "init");
    -[QLNotResponceSelectorHander setHanderClassName:](v9, "setHanderClassName:", v7);
    v10 = NSStringFromSelector(v3);
    v11 = objc_retainAutoreleasedReturnValue(v10);
    -[QLNotResponceSelectorHander setHanderSelectorName:](v9, "setHanderSelectorName:", v11);
    objc_release(v11);
    v12 = objc_msgSend(v9, "class");
    class_addMethod(v12, v3, selectorBlockFun, "v@:");
  }
  else
  {
    v13 = objc_msgSend(v4, "QLForwardingTargetForSelector:", v3);
    v9 = (QLNotResponceSelectorHander *)objc_retainAutoreleasedReturnValue(v13);
  }
  objc_release(v7);
  return (id)objc_autoreleaseReturnValue(v9);
}

如何解决：
为了避免覆盖，我们swizzle腾讯视频已经修改过的method，这样才能解决问题。
手工修改OCMethodTrace
+ (void)load
{
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        swizzle_class_method([self class], @selector(forwardingTargetForSelector:), @selector(omt_forwardingTargetForSelector:));
        swizzle_instance_method([self class], @selector(QLForwardingTargetForSelector:), @selector(omt_forwardingTargetForSelector:)); // forwardingTargetForSelector:替换成QLForwardingTargetForSelector
    });
}

这样改感觉可能存在一个问题，因为我们hook了一些类的方法，在原本的aSelector之前加了前缀(__OMTMessageTemp_XXX)，可能导致QLForwardingTargetForSelector内部判断逻辑异常，因为它内部可能会判断原本aSelector的前缀，但显然，这里aSelector的前缀被篡改了。如何处理呢？因为这种情景很少，待遇到实际问题再处理。

因为这属于腾讯视频特有的异常，并且我们并不知道除了腾讯视频之外别的app swizzle后的方法名，所以，只能根据对应app的情况手工修改，不会hardcode放到OCMethodTrace内部解决最后commit代码。

另外：
QLVideoDetailViewController打印的日志相当多，容易导致崩溃。
建议修改MDConfig.plist：
方法1：屏蔽所有类的description打印，需全局TraceFlag开启MDTraceFlagDoesNotUseDescription。
方法2：屏蔽某个类的description打印，需在USER_CLASS_LIST新增对应的类名，对应类的TraceFlag开启MDTraceFlagDoesNotUseDescription（TraceMode设置0，避免跟踪该类方法）
