### ISSUE TITLE
能给个基本使用说明？

### ISSUE THREAD

**Issue by goodcyg** [omxcodec/OCMethodTrace#2]
例如：在git的readme中给基本使用例子，不用打开你的demo单元测试一个个去看?

**Comment by omxcodec** [comment]
你可以打开内部包含的demo，然后对着readme的配置说明理解。
如果你觉得哪里还很难理解，可以具体点，我再解释。

这个配置确实会比较复杂点，首先是为了处理各种异常（当你真的想hook几百个类的时候你就会碰到这些异常），另外可以给以一些灵活调试开关

**Comment by goodcyg** [comment]
个人觉得：你的封装就是为了别人使用方便，甚至不需要了解你的实现细节，使用默认配置就能快速上手，使用你的核心功能，我使用的时候，看你这里别用到了汇编，觉得很高大上，但是我想把demo，跑起来，确没有输出我想要的结果。顿时觉得不想用了，学习成本好高。当然我知道你这个东东是干啥用的。简单几行代码，就能展示你作品的威力，这样使用起来才叫爽？降低使用门槛。

**Comment by YunsChou** [comment]
先花一两天时间好好先研究下怎么用吧
（业务不同，没必要什么都做成一句话调用）
这个确实很强大，挺好用的，感谢作者
