### ISSUE TITLE
Command CompileC failed with a nonzero exit code

### ISSUE THREAD

**Issue by bolide74** [omxcodec/OCMethodTrace#3]
你好：
我的IDE是xcode10.1，在`模拟器`环境下，直接运行你的demo可以成功跑起来，但是拉到我的项目里时，却会在编译a2a3-selectortramps-x86_64.s 时就会报一个`Command CompileC failed with a nonzero exit code` 

查了半天没查出来是啥原因，请问你知道是怎么回事吗？

**Comment by bolide74** [comment]
![image](https://user-images.githubusercontent.com/1289904/54743747-fa530800-4bff-11e9-8280-a5803f4539b4.png)

**Comment by omxcodec** [comment]
是的，我当然验证x86的时候，确实是在模拟器上跑起来，没有在真实的x86上跑。因为我没有对应的app

你可以把你相关的小一部分代码写一个代码，然后重现这个bug，然后单独发给我吗？
这样我可以帮你实际看看
