### ISSUE TITLE
在IOS11以及IOS12上，会发生崩溃

### ISSUE THREAD

**Issue by wwpp3399** [omxcodec/OCMethodTrace#5]
-[WCAccountLoginControlLogic __OMTMessageTemp_WCBaseControlLogic->init]: unrecognized selector sent to instance 0x1c0a843d0'

目标APP为微信，换成IOS10系统的话，可以正常

**Comment by omxcodec** [comment]
@wwpp3399 谢谢反馈。为了我便于查找问题，麻烦帮忙做一下下面的事情
1. 收集App运行开始的完整日志
2. 对应版本的apk
3. MDConfig.plist trace配置文件
上面的全部打包发我一下，可以发到我留下来的email。

另外，我记得微信新版本其实会做一些处理，一旦重新打包就会警告封号。
如果可以的话，怎么搭建这个环境（绕开警告）希望帮我详细描述下，便于快递定点该工具本身问题

**Comment by wwpp3399** [comment]
[


](url)

**Comment by wwpp3399** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    

    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    其实我也不知道怎么搭建环境来处理这个封号问题，我只是作为研究学习🤣，我提出的这个问题在启动的时候就会存在，详情请看日志，这是从启动到结束的所有日志
    
        
            
        
    
    
    
    

    

    

    在2019年04月28日 09:33，MichaelChen<notifications@github.com> 写道： 


@wwpp3399 谢谢反馈。为了我便于查找问题，麻烦帮忙做一下下面的事情

收集App运行开始的完整日志
对应版本的apk
MDConfig.plist trace配置文件
上面的全部打包发我一下，可以发到我留下来的email。

另外，我记得微信新版本其实会做一些处理，一旦重新打包就会警告封号。
如果可以的话，怎么搭建这个环境（绕开警告）希望帮我详细描述下，便于快递定点该工具本身问题

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

  
   从网易邮箱大师发来的云附件          微信.ipa.zip (114MB,2019年5月13日 18:56 到期)   下载
