### ISSUE TITLE
unrecognized selector sent to instance 

### ISSUE THREAD

**Issue by devhuang0714** [omxcodec/OCMethodTrace#6]
![image](https://user-images.githubusercontent.com/16683907/61126491-23651480-a4df-11e9-9912-8f67ea8cb625.png)

![image](https://user-images.githubusercontent.com/16683907/61126190-65418b00-a4de-11e9-9bb9-aa2c12e7f5bf.png)

您好，请问一下，我根据您的README配置的plist，hook某个类的所有方法，或者hook类的白名单方法，都会崩溃。能帮我看一下是哪配置的有问题吗？
微信版本 7.0.4
系统版本 iOS 12.1.4

**Comment by omxcodec** [comment]
不好意思，调试微信会被封号。我仅有一个微信号...
