### ISSUE TITLE
无法正常打印 

### ISSUE THREAD

**Issue by s88101088** [omxcodec/OCMethodTrace#7]
<img width="708" alt="截圖 2020-11-24 16 24 30" src="https://user-images.githubusercontent.com/64821575/100067692-8a376380-2e71-11eb-91b5-27f1b15d3b47.png">

已按照使用说明去设置打印
但无法打印出任何东西！！
有解决方式吗？还是那边有设置错误？

**Comment by omxcodec** [comment]
感觉没啥问题呀。你输入日志时，最好先处理一下符号，参考：
[iOS符号表恢复&逆向支付宝](http://blog.imjun.net/posts/restore-symbol-of-iOS-app/)
也看看能不能断点到那个类的某些方法。

饿

**Comment by s88101088** [comment]
也看看能不能断点到那个类的某些方法---》这个是能的
例如这个最基本的弹窗UIALRTVIEWCONTROLLER 的Setmessage方法 在code LLDB 能够断住
<img width="641" alt="截圖 2020-11-24 23 28 12" src="https://user-images.githubusercontent.com/64821575/100114769-bb815500-2eac-11eb-89ab-192b0f55755c.png">
想说利用这个来做测试但似乎不行
<img width="696" alt="截圖 2020-11-24 23 33 47" src="https://user-images.githubusercontent.com/64821575/100115478-8590a080-2ead-11eb-83e8-3e2756d103b2.png">

符号表恢复---》这个可能就是问题点了！！我这APP似乎是OC+SWIFT混编的 还原出来的部分还是乱码
在MONKEY工程底下设置内建的符号还原也设置上了
<img width="584" alt="截圖 2020-11-24 23 26 39" src="https://user-images.githubusercontent.com/64821575/100115171-29c61780-2ead-11eb-9bbe-e58432e86db8.png">
还望大佬能帮忙一下！！万分感激

**Comment by omxcodec** [comment]
1 MONKEY工程底下设置内建的符号---之前我用的时候好像失效了
2 符号表恢复一般是你需要hook或者trace那些私有类，而你这个UIAlertController好像是系统函数，不恢复好像也没啥问题
3 你写一个简单的程序，然后试下同样的配置试下？你先试下，如果这个简单的程序仍旧不能工作，那就发过来，我帮你运行下看看

**Comment by s88101088** [comment]
大佬您好：

这边我大致上可以确认了问题所在 应当是OC+SWIFT 混编造成失灵

而Monkey里头自带的符号还原其实有些还是有效的 除了被混淆以外

再来就是想问问您这边有无OC+SWIFT 能完整calss dump +符号表还原 出来的方案吗？

谷歌百度了好久都没有啥动静～～》。《。非常的郁闷

再麻烦您了 万分感激！



MichaelChen <notifications@github.com<mailto:notifications@github.com>> 於 2020年11月25日 02:28 寫道：


1 MONKEY工程底下设置内建的符号---之前我用的时候好像失效了
2 符号表恢复一般是你需要hook或者trace那些私有类，而你这个UIAlertController好像是系统函数，不恢复好像也没啥问题
3 你写一个简单的程序，然后试下同样的配置试下？你先试下，如果这个简单的程序仍旧不能工作，那就发过来，我帮你运行下看看

**Comment by omxcodec** [comment]
再来就是想问问您这边有无OC+SWIFT 能完整calss dump +符号表还原 出来的方案吗？
这个没有哦。我写这个东西的时候搞iOS都不过一年，现在也基本不写ObjC程序了，SWIFT都没写过。

你可以看看frida-trace的方案，也可以trace。那个是不是可以trace混淆后的调用呢？我记得Android Java是可以的。
地址： https://frida.re/docs/frida-trace/

还有，不一定非要全部通过trace来解决问题呀
1一些关键加解密，弹窗都是系统函数或者第三方函数，是否可以断点那些看看情况呢。网络函数调用断点一下，然后回溯堆栈。
2 strings APP_OR_LIB ，搜下是否有什么特殊字符串
3 IDA静态分析按F5看看
...
