### ISSUE TITLE
打扰下。我这样子配置一直不打印任何日志。

### ISSUE THREAD

**Issue by LiuSky** [omxcodec/OCMethodTrace#8]
[
![截屏2024-03-06 09 57 59](https://github.com/omxcodec/OCMethodTrace/assets/3087745/fe755d09-22fc-44e4-88bb-90b17258cf1b)
MethodTrace] logLevel: 1: logWhen: 0 traceFlag: 2 traceObject: 2(用户类)
[MethodTrace] Dump 用户类 class list info: 
[MethodTrace] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[MethodTrace] ClassList[00000]: <MDTraceClassInfo: 0x281ddac10 name: BaseMsgContentViewController source: 1 mode: 0 flag: 1 methodList: (
)>
[MethodTrace] ClassList[00001]: <MDTraceClassInfo: 0x281ddac40 name: VoIPCallerViewController source: 1 mode: 1 flag: 0 methodList: (
)>
[MethodTrace] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[MethodTrace]  
[MethodTrace] ////////////////////////////////////////////////////////////////////////////////
[MethodTrace]  
[MethodTrace] ClassList[00000]: BaseMsgContentViewController
[MethodTrace] ClassList[00001]: VoIPCallerViewController
[MethodTrace]  
[MethodTrace] ////////////////////////////////////////////////////////////////////////////////
[MethodTrace]

**Comment by omxcodec** [comment]
你直接把整个配置的plist文件发给我，然后发一下你的app名称和对应版本号，最好是当前苹果商店直接可以下载的。

**Comment by LiuSky** [comment]
[配置.zip](https://github.com/omxcodec/OCMethodTrace/files/14633184/default.zip)
微信8.0.48 
@omxcodec

**Comment by omxcodec** [comment]
这个配置可以呀，我试了一下，函数跟踪没啥问题呀。

是不是你编译的时候不是DEBUG模式。
因为OCMethodTrace项目的代码里有如下代码
- (void)traceMethodWithClass:(Class)cls
                   condition:(OMTConditionBlock)condition
                      before:(OMTBeforeBlock)before
                       after:(OMTAfterBlock)after
{
#ifndef DEBUG
    return;
#endif

也就是非DEBUG模式就跳过跟踪了。

**Comment by LiuSky** [comment]
好。我看下。谢谢。
